screen_error: don't reset on button click during BSOD or RSOD
User experience is better, intuitively user may press button to silence the printer during BSOD/RSOD, but this should not generate reset. Reset button needs to be pressed instead.

BFW-6539